server.port=8888
spring.application.name=config-server

spring.profiles.active=native
spring.cloud.config.server.native.search-locations=file:///c:/Users/thula/P3-Ant/RevWorkForce-P3/config-repo-files/